#!/bin/bash

# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

cat "../versions.txt" | while read VERSION
do
    # The new image tag will include the version of ubuntu
	IMAGE_TAG="${DOCKER_REPO}:${VERSION}"

	echo "docker build -f Dockerfile --build-arg VERSION=${VERSION} -t ${IMAGE_TAG} ."
	docker build -f Dockerfile --build-arg VERSION=${VERSION} -t ${IMAGE_TAG} .
done
